### ISSUE TITLE
Couldn't load SideBar on some websites

### ISSUE THREAD

**Issue by mkarang** [mingyaulee/Blazor.BrowserExtension.Samples#1]
First of all, thank you so very much for making this. I find it super helpful.

I'm able to load the Sidebar and toggle it on some websites, but not on all. For example on Google Finance, the Toggle button doesn't show up and I'm seeing these errors
 
![image](https://user-images.githubusercontent.com/86509298/202050442-8f77d369-bc33-40e8-bec9-a3917831a4ce.png)
![image](https://user-images.githubusercontent.com/86509298/202050389-d8cdc9d5-c5e2-432e-b7dc-ec87b04da58a.png)

Is the above hard to fix? I'm considering to just stay on manifest V2 for the time being (because the SideBar from manifest V2 didn't have this problem).

Thanks again!

**Comment by mingyaulee** [comment]
Issue tracked from https://github.com/mingyaulee/Blazor.BrowserExtension/issues/47
