### ISSUE TITLE
Extension gets installed but is grayed out on the Extensions menu

### ISSUE THREAD

**Issue by squideyes** [mingyaulee/Blazor.BrowserExtension.Samples#2]
Hi!  

I installed your SidebarUsingContentScripts extension following your instructions in your README.md file (for Chrome) but the extension is grayed out.  And yes, it is both enabled and I did reload the browser before testing.

Any help in this regard would be greatly appreciated...

**Comment by mingyaulee** [comment]
Hi there! I don't think I understand what you are referring to, can you provide a screenshot to show the what's grayed out?

**Comment by squideyes** [comment]
Thanks for the quick reply.  As shown below, the "Sidebar with ContextScripts" menu item is grayed out:


![Sidebar Extension Grayed Out](https://user-images.githubusercontent.com/4204316/213900183-d89932dd-f716-473b-b594-fb89d6398a9b.png)

**Comment by mingyaulee** [comment]
This menu item is only available if there is any `action` registered in the manifest, which will show a popup when clicked. The sidebar example is showing how you can have Blazor injected into a page when using content script. You can see this if you navigate to Google's home page, there is a button that is injected and will show the sidebar when clicked.

**Comment by squideyes** [comment]
I understand.  That worked perfectly.  Thanks….
